name: Deploy Infrastructure
on:
  push:
    branches: [main]
    paths:
      - 'infrastructure/terraform/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    - run: terraform init
      working-directory: ./infrastructure/terraform
    - run: terraform apply -auto-approve
      working-directory: ./infrastructure/terraform
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
