version: '3'
services:
  backend:
    image: todo-backend
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
  frontend:
    image: todo-frontend
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    links:
      - backend
