apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecomm-rolebinding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: ecomm-sa
  namespace: prod
roleRef:
  kind: Role
  name: ecomm-role
  apiGroup: rbac.authorization.k8s.io
