apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecomm-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ range ,  := .Values.ingress.annotations }}
    {{  }}: {{  | quote }}
    {{ end }}
spec:
  ingressClassName: alb
  rules:
  {{ range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{ range .paths }}
      - path: {{ .path }}
        pathType: Prefix
        backend:
          service:
            name: {{ .backend }}-service
            port:
              number: {{ $.Values.backend.port }}
      {{ end }}
  {{ end }}
